# Generated by Django 5.1.3 on 2024-12-01 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0003_alter_stockquote_managers"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stockquote",
            old_name="compony",
            new_name="company",
        ),
    ]
